### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by alvarogf97** [yabirgb/zinat#10]
which dependencies should I install?

**Comment by yabirgb** [comment]
Hi @alvarogf97 . In the [Pipfile](https://github.com/yabirgb/zinat/blob/master/Pipfile) you have all the libraries used by Python. At the moment I'm writting a guide of the project at the official [documentation](https://github.com/ZinatProject/documentation/blob/master/structure.md) and by the end of the weekend I want to have a how to install guide. The only external resources needed are a redis server and if you want something to serve the images (I've uploaded a config file for nginx as a basic example [here](https://github.com/yabirgb/zinat/blob/master/src/configs/nginx.conf), this is the one I use to test the app ) There are a pair of hardcoded paths that I have detected and need to be changed and moved to the config files (sorry for this, is one of my priorities now). If you need something else don't doubt to comment here :smile:

**Comment by yabirgb** [comment]
Also if you are interested @alvarogf97, I'm creating a [client](https://github.com/ZinatProject/client) using vue. It has limited functionality but you can go to /login and get access to different functiionalities
